local WING_SPAN = 34.3 -- m
local WING_AREA = 124.6 -- m^2
local WING_ASPECT_RATIO = 9.45
local WING_TAPER_RATIO = 0.16
local WING_ROOT_CHORD = 7.88 -- m
local WING_TIP_CHORD = 1.25 -- m
local WING_MEAN_AERODYNAMIC_CHORD = 3.96 -- m
local WING_DIHEDRAL_ANGLE = 6 -- degrees
local WING_ONE_FOURTH_CHORD_SWEEP_ANGLE = 25 -- degrees

local FLAP_SPAN = 0.6 -- m
local FLAP_AREA = 0.3 -- m^2

local FIN_SPAN = 7.16 -- m
local FIN_AREA = 26.44 -- m^2
local FIN_RUDDER_AREA = 5.22 -- m^2
local FIN_ASPECT_RATIO = 1.91
local FIN_TAPER_RATIO = 0.27
local FIN_SWEEP_ANGLE = 35 -- degrees

local HORIZONTAL_STABILIZER_SPAN = 14.35 -- m
local HORIZONTAL_STABILIZER_TAILPLANE_AREA = 32.78 -- m^2
local HORIZONTAL_STABILIZER_ELEVATORS_AREA = 6.55 -- m^2
local HORIZONTAL_STABILIZER_ASPECT_RATIO = 6.55
local HORIZONTAL_STABILIZER_TAPER_RATIO = 0.2
local HORIZONTAL_DIHEDRAL_ANGLE = 7
local HORIZONTAL_STABILIZER_ONE_FOURTH_CHORD_SWEEP_ANGLE = 30 -- degrees
